networks:
  db_network:  # Network for MongoDB-related services
    driver: bridge
  api_network:  # Network for API-related services
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:  
      - mongo-data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d # Initialization scripts (runs only once)
    networks:
      - db_network 

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    networks:
      - db_network 
    depends_on:
      - mongo

  flask-app:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:admin@mongodb_container:27017/weatherDB
    depends_on:
      - mongo
    networks:
      - api_network  
      - db_network

volumes: 
  mongo-data:
